services:
  db:
    image: mysql:8.4.5
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: placies
      MYSQL_PASSWORD: placies
      MYSQL_DATABASE: placies

  redis:
    image: redis:latest
    ports:
      - 6379:6379/tcp

volumes:
  mysql-data:
    driver: local
  pgadmin:
    driver: local
