services:
  db:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    ports:
      - 5432:5432/tcp
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: placies
      POSTGRES_PASSWORD: placies
      POSTGRES_DB: placies
      DB_EXTENSION: postgis

  redis:
    image: redis:latest
    ports:
      - 6379:6379/tcp

volumes:
  postgres-data:
    driver: local
  pgadmin:
    driver: local
